# name: Mock-Interview Schedule

# on:
#  push:
#   branches:
#     - main

#  pull_request:
#   branches:
#    - main

#  schedule:
#    - cron: '0 6 * * *'
#    - cron: '15 6 * * *'

# jobs:
#   smoke-testing:
#       runs-on: ubuntu-latest

#       steps:
#         - uses: actions/checkout@v4.2.1
#         - uses: actions/setup-node@v4.1.0
#           with:
#             node-version: 22
#             cache: npm
#         - run: npm ci
#         - run: npx playwright install --with-deps chromium

#         - run: npx playwright test tests/smokeTest/Loginpage.spec.js --project=chromium
#           if: github.event_name == 'schedule' && github.event.schedule == '0 6 * * *'


#         - run: npx playwright test tests/smokeTest/Register.spec.js --project=chromium 
#           if: github.event_name == 'schedule' && github.event.schedule == '15 6 * * *'


name: Mock-Interview Schedule

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    # 11:30 AM IST
    - cron: '0 6 * * *'

    # 11:45 AM IST
    - cron: '15 6 * * *'

jobs:
  smoke-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npx playwright install --with-deps chromium

      - name: Run Login Test - 11:30 AM IST
        if: github.event_name == 'schedule' && github.event.schedule == '0 6 * * *'
        run: npx playwright test tests/smokeTest/Loginpage.spec.js --project=chromium

      - name: Run Register Test - 11:45 AM IST
        if: github.event_name == 'schedule' && github.event.schedule == '15 6 * * *'
        run: npx playwright test tests/smokeTest/Register.spec.js --project=chromium