name: Mock-Interview Schedule

on:
 push:
  branches:
    - main

 pull_request:
  branches:
   - main

 schedule:
   - cron: '30 23 * * *'
     timezone: 'Asia/Kolkata'

   - cron: '45 23 * * *'
     timezone: 'Asia/Kolkata'
     
   - cron: '50 23 * * *'
     timezone: 'Asia/Kolkata'

jobs:
  smoke-testing:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4.2.1
        - uses: actions/setup-node@v4.1.0
          with:
            node-version: 22
            cache: npm
        - run: npm ci
        - run: npx playwright install --with-deps chromium

        - if: github.event_name == 'schedule' && github.event.schedule == '30 23 * * *'
          run: npx playwright test tests/smokeTest/Loginpage.spec.js --project=chromium


        - if: github.event_name == 'schedule' && github.event.schedule == '45 23 * * *'
          run: npx playwright test tests/smokeTest/Register.spec.js --project=chromium 

        - if: github.event_name == 'schedule' && github.event.schedule == '50 23 * * *'
          run: npx playwright test tests/smokeTest/InterviweTest.spec.js --project=chromium

